import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const words = [
  // ===== FRUIT (15) =====
  { word: 'apple', phonetic: '/ˈæp.əl/', meaning: '苹果', category: 'fruit', difficulty: 'easy', level: 1 },
  { word: 'banana', phonetic: '/bəˈnæn.ə/', meaning: '香蕉', category: 'fruit', difficulty: 'easy', level: 1 },
  { word: 'grape', phonetic: '/ɡreɪp/', meaning: '葡萄', category: 'fruit', difficulty: 'easy', level: 1 },
  { word: 'strawberry', phonetic: '/ˈstrɔː.bər.i/', meaning: '草莓', category: 'fruit', difficulty: 'medium', level: 3 },
  { word: 'watermelon', phonetic: '/ˈwɔː.tər.mel.ən/', meaning: '西瓜', category: 'fruit', difficulty: 'medium', level: 3 },
  { word: 'pineapple', phonetic: '/ˈpaɪn.æp.əl/', meaning: '菠萝', category: 'fruit', difficulty: 'medium', level: 3 },
  { word: 'mango', phonetic: '/ˈmæŋ.ɡoʊ/', meaning: '芒果', category: 'fruit', difficulty: 'easy', level: 2 },
  { word: 'peach', phonetic: '/piːtʃ/', meaning: '桃子', category: 'fruit', difficulty: 'easy', level: 1 },
  { word: 'pear', phonetic: '/per/', meaning: '梨', category: 'fruit', difficulty: 'easy', level: 1 },
  { word: 'lemon', phonetic: '/ˈlem.ən/', meaning: '柠檬', category: 'fruit', difficulty: 'easy', level: 2 },
  { word: 'cherry', phonetic: '/ˈtʃer.i/', meaning: '樱桃', category: 'fruit', difficulty: 'easy', level: 2 },
  { word: 'blueberry', phonetic: '/ˈbluː.be.ri/', meaning: '蓝莓', category: 'fruit', difficulty: 'medium', level: 3 },
  { word: 'coconut', phonetic: '/ˈkoʊ.kə.nʌt/', meaning: '椰子', category: 'fruit', difficulty: 'medium', level: 2 },
  { word: 'avocado', phonetic: '/ˌæv.əˈkɑː.doʊ/', meaning: '牛油果', category: 'fruit', difficulty: 'hard', level: 5 },
  { word: 'apricot', phonetic: '/əˈprɒt/', meaning: '杏子', category: 'fruit', difficulty: 'hard', level: 5 },

  // ===== ANIMAL (15) =====
  { word: 'dog', phonetic: '/dɔːɡ/', meaning: '狗', category: 'animal', difficulty: 'easy', level: 1 },
  { word: 'cat', phonetic: '/kæt/', meaning: '猫', category: 'animal', difficulty: 'easy', level: 1 },
  { word: 'elephant', phonetic: '/ˈel.ɪ.fənt/', meaning: '大象', category: 'animal', difficulty: 'medium', level: 3 },
  { word: 'tiger', phonetic: '/ˈtaɪ.ɡər/', meaning: '老虎', category: 'animal', difficulty: 'easy', level: 2 },
  { word: 'lion', phonetic: '/ˈlaɪ.ən/', meaning: '狮子', category: 'animal', difficulty: 'easy', level: 2 },
  { word: 'bear', phonetic: '/ber/', meaning: '熊', category: 'animal', difficulty: 'easy', level: 1 },
  { word: 'rabbit', phonetic: '/ˈræb.ɪt/', meaning: '兔子', category: 'animal', difficulty: 'easy', level: 2 },
  { word: 'monkey', phonetic: '/ˈmʌŋ.ki/', meaning: '猴子', category: 'animal', difficulty: 'easy', level: 2 },
  { word: 'penguin', phonetic: '/ˈpeŋ.ɡwɪn/', meaning: '企鹅', category: 'animal', difficulty: 'medium', level: 3 },
  { word: 'giraffe', phonetic: '/dʒəˈræf/', meaning: '长颈鹿', category: 'animal', difficulty: 'medium', level: 3 },
  { word: 'dolphin', phonetic: '/ˈdɒl.fɪn/', meaning: '海豚', category: 'animal', difficulty: 'medium', level: 3 },
  { word: 'butterfly', phonetic: '/ˈbʌt.ər.flaɪ/', meaning: '蝴蝶', category: 'animal', difficulty: 'medium', level: 4 },
  { word: 'squirrel', phonetic: '/ˈskwɜːr.əl/', meaning: '松鼠', category: 'animal', difficulty: 'hard', level: 4 },
  { word: 'kangaroo', phonetic: '/ˌkæŋ.ɡəˈruː/', meaning: '袋鼠', category: 'animal', difficulty: 'hard', level: 4 },
  { word: 'panda', phonetic: '/ˈpæn.də/', meaning: '熊猫', category: 'animal', difficulty: 'easy', level: 1 },

  // ===== COLOR (10) =====
  { word: 'crimson', phonetic: '/ˈkrɪm.zən/', meaning: '深红色', category: 'color', difficulty: 'hard', level: 5 },
  { word: 'turquoise', phonetic: '/ˈtɜːr.kwɔːz/', meaning: '绿松石色', category: 'color', difficulty: 'hard', level: 5 },
  { word: 'magenta', phonetic: '/məˈdzen.tə/', meaning: '品红色', category: 'color', difficulty: 'hard', level: 5 },
  { word: 'lavender', phonetic: '/ˈlæv.ən.dər/', meaning: '淡紫色', category: 'color', difficulty: 'medium', level: 4 },
  { word: 'coral', phonetic: '/ˈkɔːr.əl/', meaning: '珊瑚色', category: 'color', difficulty: 'medium', level: 3 },
  { word: 'olive', phonetic: '/ˈɒl.ɪv/', meaning: '橄榄绿', category: 'color', difficulty: 'medium', level: 3 },
  { word: 'maroon', phonetic: '/məˈruːn/', meaning: '栗色', category: 'color', difficulty: 'medium', level: 3 },
  { word: 'beige', phonetic: '/beɪʒ/', meaning: '米色', category: 'color', difficulty: 'medium', level: 3 },
  { word: 'ivory', phonetic: '/ˈaɪ.vər.i/', meaning: '象牙白', category: 'color', difficulty: 'medium', level: 4 },
  { word: 'gold', phonetic: '/ɡoʊld/', meaning: '金色', category: 'color', difficulty: 'easy', level: 2 },

  // ===== NUMBER (10) =====
  { word: 'first', phonetic: '/fɜːrst/', meaning: '第一', category: 'number', difficulty: 'easy', level: 2 },
  { word: 'second', phonetic: '/ˈsek.ənd/', meaning: '第二', category: 'number', difficulty: 'easy', level: 2 },
  { word: 'third', phonetic: '/θɜːrd/', meaning: '第三', category: 'number', difficulty: 'easy', level: 2 },
  { word: 'hundred', phonetic: '/ˈhʌn.drəd/', meaning: '百', category: 'number', difficulty: 'easy', level: 2 },
  { word: 'thousand', phonetic: '/ˈθaʊ.zənd/', meaning: '千', category: 'number', difficulty: 'easy', level: 2 },
  { word: 'million', phonetic: '/ˈmɪl.jən/', meaning: '百万', category: 'number', difficulty: 'medium', level: 3 },
  { word: 'billion', phonetic: '/ˈbɪl.jən/', meaning: '十亿', category: 'number', difficulty: 'medium', level: 3 },
  { word: 'half', phonetic: '/hæf/', meaning: '一半', category: 'number', difficulty: 'easy', level: 1 },
  { word: 'quarter', phonetic: '/ˈkwɔːr.t̬ɚ/', meaning: '四分之一', category: 'number', difficulty: 'medium', level: 3 },
  { word: 'double', phonetic: '/ˈdʌb.əl/', meaning: '双倍', category: 'number', difficulty: 'easy', level: 2 },

  // ===== FAMILY (10) =====
  { word: 'parent', phonetic: '/ˈper.ənt/', meaning: '父母', category: 'family', difficulty: 'easy', level: 2 },
  { word: 'son', phonetic: '/sʌn/', meaning: '儿子', category: 'family', difficulty: 'easy', level: 1 },
  { word: 'daughter', phonetic: '/ˈdɔːt̬.ər/', meaning: '女儿', category: 'family', difficulty: 'easy', level: 1 },
  { word: 'husband', phonetic: '/ˈhʌz.bənd/', meaning: '丈夫', category: 'family', difficulty: 'easy', level: 2 },
  { word: 'wife', phonetic: '/waɪf/', meaning: '妻子', category: 'family', difficulty: 'easy', level: 1 },
  { word: 'grandparent', phonetic: '/ˈɡræn.per.ənt/', meaning: '祖父母', category: 'family', difficulty: 'medium', level: 3 },
  { word: 'grandson', phonetic: '/ˈɡræn.sʌn/', meaning: '孙子', category: 'family', difficulty: 'medium', level: 3 },
  { word: 'granddaughter', phonetic: '/ˌɡrænˈdɔːt̬.ər/', meaning: '孙女', category: 'family', difficulty: 'hard', level: 4 },
  { word: 'stepfather', phonetic: '/ˈstep.fɑː.ðər/', meaning: '继父', category: 'family', difficulty: 'hard', level: 4 },
  { word: 'inlaw', phonetic: '/ˈɪnˌlɔː/', meaning: '姻亲', category: 'family', difficulty: 'hard', level: 5 },

  // ===== FOOD (20) =====
  { word: 'noodle', phonetic: '/ˈnuː.dəl/', meaning: '面条', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'soup', phonetic: '/suːp/', meaning: '汤', category: 'food', difficulty: 'easy', level: 1 },
  { word: 'salad', phonetic: '/ˈsæl.əd/', meaning: '沙拉', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'pizza', phonetic: '/ˈpiːt.sə/', meaning: '披萨', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'burger', phonetic: '/ˈbɜːr.ɡər/', meaning: '汉堡', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'cake', phonetic: '/keɪk/', meaning: '蛋糕', category: 'food', difficulty: 'easy', level: 1 },
  { word: 'cookie', phonetic: '/ˈkʊk.i/', meaning: '饼干', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'cheese', phonetic: '/tʃiːz/', meaning: '奶酪', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'butter', phonetic: '/ˈbʌt.ər/', meaning: '黄油', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'coffee', phonetic: '/ˈkɒf.i/', meaning: '咖啡', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'juice', phonetic: '/dʒuːs/', meaning: '果汁', category: 'food', difficulty: 'easy', level: 1 },
  { word: 'pasta', phonetic: '/ˈpæs.tə/', meaning: '意大利面', category: 'food', difficulty: 'medium', level: 3 },
  { word: 'steak', phonetic: '/steɪk/', meaning: '牛排', category: 'food', difficulty: 'medium', level: 3 },
  { word: 'pancake', phonetic: '/ˈpæn.keɪk/', meaning: '煎饼', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'sandwich', phonetic: '/ˈsæn.wɪtʃ/', meaning: '三明治', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'chocolate', phonetic: '/ˈtʃɒk.lət/', meaning: '巧克力', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'candy', phonetic: '/ˈkæn.di/', meaning: '糖果', category: 'food', difficulty: 'easy', level: 1 },
  { word: 'honey', phonetic: '/ˈhʌn.i/', meaning: '蜂蜜', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'salt', phonetic: '/sɔːlt/', meaning: '盐', category: 'food', difficulty: 'easy', level: 1 },
  { word: 'pepper', phonetic: '/ˈpep.ər/', meaning: '胡椒', category: 'food', difficulty: 'easy', level: 2 },

  // ===== GENERAL (20) =====
  { word: 'time', phonetic: '/taɪm/', meaning: '时间', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'day', phonetic: '/deɪ/', meaning: '天', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'night', phonetic: '/naɪt/', meaning: '夜晚', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'music', phonetic: '/ˈmjuː.zɪk/', meaning: '音乐', category: 'general', difficulty: 'easy', level: 2 },
  { word: 'beautiful', phonetic: '/ˈbjuː.tɪ.fəl/', meaning: '美丽的', category: 'general', difficulty: 'medium', level: 3 },
  { word: 'important', phonetic: '/ɪmˈpɔːr.tənt/', meaning: '重要的', category: 'general', difficulty: 'medium', level: 3 },
  { word: 'different', phonetic: '/ˈdɪf.ər.ənt/', meaning: '不同的', category: 'general', difficulty: 'medium', level: 3 },
  { word: 'work', phonetic: '/wɜːrk/', meaning: '工作', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'money', phonetic: '/ˈmʌn.i/', meaning: '钱', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'city', phonetic: '/ˈsɪt.i/', meaning: '城市', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'country', phonetic: '/ˈkʌn.tri/', meaning: '国家', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'love', phonetic: '/lʌv/', meaning: '爱', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'book', phonetic: '/bʊk/', meaning: '书', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'water', phonetic: '/ˈwɔː.tər/', meaning: '水', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'friend', phonetic: '/frend/', meaning: '朋友', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'school', phonetic: '/skuːl/', meaning: '学校', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'house', phonetic: '/haʊs/', meaning: '房子', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'dream', phonetic: '/driːm/', meaning: '梦想', category: 'general', difficulty: 'easy', level: 2 },

  // ===== WEATHER (10) =====
  { word: 'sunny', phonetic: '/ˈsʌn.i/', meaning: '晴朗的', category: 'weather', difficulty: 'easy', level: 1 },
  { word: 'rainy', phonetic: '/ˈreɪ.ni/', meaning: '下雨的', category: 'weather', difficulty: 'easy', level: 1 },
  { word: 'cloudy', phonetic: '/ˈklaʊ.di/', meaning: '多云的', category: 'weather', difficulty: 'easy', level: 1 },
  { word: 'windy', phonetic: '/ˈwɪn.di/', meaning: '有风的', category: 'weather', difficulty: 'easy', level: 2 },
  { word: 'snowy', phonetic: '/ˈsnoʊ.i/', meaning: '下雪的', category: 'weather', difficulty: 'easy', level: 2 },
  { word: 'storm', phonetic: '/stɔːrm/', meaning: '暴风雨', category: 'weather', difficulty: 'medium', level: 3 },
  { word: 'fog', phonetic: '/fɒɡ/', meaning: '雾', category: 'weather', difficulty: 'easy', level: 2 },
  { word: 'rainbow', phonetic: '/ˈreɪn.boʊ/', meaning: '彩虹', category: 'weather', difficulty: 'medium', level: 3 },
  { word: 'lightning', phonetic: '/ˈlaɪt.nɪŋ/', meaning: '闪电', category: 'weather', difficulty: 'hard', level: 4 },
  { word: 'temperature', phonetic: '/ˈtem.pər.ə.tʃər/', meaning: '温度', category: 'weather', difficulty: 'hard', level: 4 },

  // ===== MOOD (10) =====
  { word: 'happy', phonetic: '/ˈhæp.i/', meaning: '快乐的', category: 'mood', difficulty: 'easy', level: 1 },
  { word: 'sad', phonetic: '/sæd/', meaning: '悲伤的', category: 'mood', difficulty: 'easy', level: 1 },
  { word: 'angry', phonetic: '/ˈæŋ.ɡri/', meaning: '生气的', category: 'mood', difficulty: 'easy', level: 1 },
  { word: 'excited', phonetic: '/ɪkˈsaɪ.tɪd/', meaning: '兴奋的', category: 'mood', difficulty: 'medium', level: 3 },
  { word: 'nervous', phonetic: '/ˈnɜːr.vəs/', meaning: '紧张的', category: 'mood', difficulty: 'medium', level: 3 },
  { word: 'calm', phonetic: '/kɑːm/', meaning: '平静的', category: 'mood', difficulty: 'easy', level: 2 },
  { word: 'bored', phonetic: '/bɔːrd/', meaning: '无聊的', category: 'mood', difficulty: 'easy', level: 2 },
  { word: 'proud', phonetic: '/praʊd/', meaning: '自豪的', category: 'mood', difficulty: 'medium', level: 3 },
  { word: 'afraid', phonetic: '/əˈfreɪd/', meaning: '害怕的', category: 'mood', difficulty: 'easy', level: 2 },
  { word: 'surprised', phonetic: '/sərˈpraɪzd/', meaning: '惊讶的', category: 'mood', difficulty: 'medium', level: 4 },

  // ===== SPORT (10) =====
  { word: 'run', phonetic: '/rʌn/', meaning: '跑步', category: 'sport', difficulty: 'easy', level: 1 },
  { word: 'swim', phonetic: '/swɪm/', meaning: '游泳', category: 'sport', difficulty: 'easy', level: 1 },
  { word: 'jump', phonetic: '/dʒʌmp/', meaning: '跳跃', category: 'sport', difficulty: 'easy', level: 1 },
  { word: 'basketball', phonetic: '/ˈbæs.kɪt.bɔːl/', meaning: '篮球', category: 'sport', difficulty: 'medium', level: 3 },
  { word: 'football', phonetic: '/ˈfʊt.bɔːl/', meaning: '足球', category: 'sport', difficulty: 'easy', level: 2 },
  { word: 'tennis', phonetic: '/ˈten.ɪs/', meaning: '网球', category: 'sport', difficulty: 'medium', level: 3 },
  { word: 'cycling', phonetic: '/ˈsaɪ.klɪŋ/', meaning: '骑行', category: 'sport', difficulty: 'medium', level: 3 },
  { word: 'skiing', phonetic: '/ˈskiː.ɪŋ/', meaning: '滑雪', category: 'sport', difficulty: 'medium', level: 4 },
  { word: 'exercise', phonetic: '/ˈek.sər.saɪz/', meaning: '锻炼', category: 'sport', difficulty: 'medium', level: 4 },
  { word: 'match', phonetic: '/mætʃ/', meaning: '比赛', category: 'sport', difficulty: 'easy', level: 2 },
];

const exampleSentences: Record<string, string> = {
  apple: 'I eat an apple every day for a healthy lifestyle.',
  banana: 'Bananas are rich in potassium and very delicious.',
  grape: 'She picked some purple grapes from the vine.',
  strawberry: 'Strawberries with cream are my favorite dessert.',
  watermelon: 'Watermelon is the perfect summer fruit.',
  pineapple: 'Pineapple goes great on pizza.',
  mango: 'Mango smoothies are so refreshing.',
  peach: 'The ripe peach is soft and sweet.',
  pear: 'I bought a bag of pears at the market.',
  lemon: 'Add some lemon juice to your water.',
  cherry: 'Cherry blossoms bloom in spring.',
  blueberry: 'Blueberries are packed with antioxidants.',
  coconut: 'Coconut water is very hydrating.',
  avocado: 'Avocado toast is popular among young people.',
  apricot: 'Apricots are small orange fruits.',
  dog: 'My dog loves to play fetch in the park.',
  cat: 'The cat is sleeping peacefully on the sofa.',
  elephant: 'Elephants are the largest land animals on Earth.',
  tiger: 'Tigers are powerful and majestic creatures.',
  lion: 'The lion is known as the king of the jungle.',
  bear: 'Bears hibernate during the cold winter months.',
  rabbit: 'The rabbit hops quickly across the meadow.',
  monkey: 'Monkeys love to swing from tree to tree.',
  penguin: 'Penguins cannot fly but they are excellent swimmers.',
  giraffe: 'Giraffes have the longest necks of any animal.',
  dolphin: 'Dolphins are among the smartest animals in the ocean.',
  butterfly: 'A beautiful butterfly landed on the flower.',
  squirrel: 'The squirrel gathered nuts for the winter.',
  kangaroo: 'Kangaroos carry their babies in a pouch.',
  panda: 'Pandas spend most of their day eating bamboo.',
  crimson: 'The crimson sunset painted the sky in brilliant colors.',
  turquoise: 'She wore a stunning turquoise necklace.',
  magenta: 'The magenta flowers stood out against the green leaves.',
  lavender: 'The field of lavender smelled wonderful.',
  coral: 'Coral reefs are home to many sea creatures.',
  olive: 'Olive oil is healthy and delicious.',
  maroon: 'He drove a maroon-colored car.',
  beige: 'The walls were painted a soft beige color.',
  ivory: 'The ivory wedding dress looked elegant.',
  gold: 'She received a gold medal for her achievement.',
  first: 'This is my first time visiting Beijing.',
  second: 'Take the second turn on the left.',
  third: 'He finished in third place in the race.',
  hundred: 'The book has over a hundred pages.',
  thousand: 'A thousand stars shone brightly in the sky.',
  million: 'One million people attended the concert.',
  billion: 'The company is worth several billion dollars.',
  half: 'Cut the cake in half, please.',
  quarter: 'I\'d like a quarter pound of beef.',
  double: 'Double the recipe for a bigger batch.',
  parent: 'Every parent wants the best for their child.',
  son: 'Her son just started kindergarten.',
  daughter: 'His daughter won the art competition.',
  husband: 'She introduced her husband to her colleagues.',
  wife: 'The couple has been married for twenty years.',
  grandparent: 'My grandparents tell the best stories.',
  grandson: 'His grandson visits him every weekend.',
  granddaughter: 'She dotes on her granddaughter.',
  stepfather: 'Her stepfather supported her dreams.',
  inlaw: 'I am meeting my inlaws for dinner tonight.',
  noodle: 'I love eating hot noodles in winter.',
  soup: 'Mom made chicken soup for me.',
  salad: 'I ordered a garden salad for lunch.',
  pizza: 'Let\'s order a pepperoni pizza tonight.',
  burger: 'I\'ll have a cheeseburger with fries.',
  cake: 'We celebrated with a chocolate birthday cake.',
  cookie: 'Mom baked chocolate chip cookies.',
  cheese: 'I love melted cheese on toast.',
  butter: 'Add some butter to the pan.',
  coffee: 'I need my morning cup of coffee.',
  juice: 'Fresh orange juice is the best.',
  pasta: 'Spaghetti is my favorite Italian pasta.',
  steak: 'The steak was cooked to perfection.',
  pancake: 'Fluffy pancakes with maple syrup!',
  sandwich: 'I made a turkey sandwich for lunch.',
  chocolate: 'Dark chocolate is healthier than milk chocolate.',
  candy: 'Children love candy on Halloween.',
  honey: 'Honey is a natural sweetener.',
  salt: 'Please pass me the salt.',
  pepper: 'Add some black pepper to taste.',
  time: 'Time flies when you are having fun.',
  day: 'What a beautiful sunny day!',
  night: 'Good night, sleep well.',
  music: 'I enjoy listening to classical music.',
  happy: 'She looks very happy today.',
  beautiful: 'The sunset was absolutely beautiful.',
  important: 'Education is very important for everyone.',
  different: 'They have different opinions on the matter.',
  weather: 'The weather is nice today for a walk.',
  work: 'He goes to work by bus every day.',
  money: 'Money cannot buy happiness.',
  city: 'New York is a vibrant and exciting city.',
  country: 'China is a large and diverse country.',
  love: 'Love makes the world go round.',
  book: 'I am reading an interesting book right now.',
  water: 'Please give me a glass of water.',
  friend: 'She is my best friend since childhood.',
  school: 'The children go to school every weekday.',
  house: 'They live in a cozy little house.',
  dream: 'Never give up on your dreams.',
  // weather
  sunny: 'It is a bright and sunny day today.',
  rainy: 'Take an umbrella because it is rainy outside.',
  cloudy: 'The sky is very cloudy this morning.',
  windy: 'It is too windy to fly a kite safely.',
  snowy: 'The mountain looks beautiful when it is snowy.',
  storm: 'A big storm is coming from the ocean.',
  fog: 'The fog is so thick I cannot see the road.',
  rainbow: 'After the rain, a beautiful rainbow appeared.',
  lightning: 'The lightning lit up the whole sky.',
  temperature: 'The temperature today is very high.',
  // mood
  sad: 'She felt sad when her friend moved away.',
  angry: 'He was angry because he lost his keys.',
  excited: 'The children are excited about the field trip.',
  nervous: 'I always feel nervous before an exam.',
  calm: 'Take a deep breath and stay calm.',
  bored: 'He was bored during the long meeting.',
  proud: 'Her parents are very proud of her success.',
  afraid: 'She is afraid of the dark.',
  surprised: 'I was surprised by the birthday gift.',
  // sport
  run: 'I run every morning to stay healthy.',
  swim: 'She can swim across the pool very fast.',
  jump: 'The cat can jump over the fence.',
  basketball: 'He plays basketball with his friends after school.',
  football: 'Football is the most popular sport in the world.',
  tennis: 'She won the tennis match yesterday.',
  cycling: 'Cycling is a fun way to explore the city.',
  skiing: 'We go skiing in the mountains every winter.',
  exercise: 'Regular exercise keeps your body strong.',
  match: 'The football match starts at three o\'clock.',
};

async function main() {
  console.log('🌱 Seeding database with 100 words...');

  // Create a default user
  const user = await prisma.user.upsert({
    where: { username: 'demo_user' },
    update: {},
    create: {
      username: 'demo_user',
      streak: 0,
      totalXP: 0,
    },
  });
  console.log('✅ Default user created:', user.username);

  // Create words
  for (const w of words) {
    const key = w.word.toLowerCase();
    await prisma.word.create({
      data: {
        ...w,
        example: exampleSentences[key] || `This is an example sentence with "${w.word}".`,
      },
    });
  }
  console.log(`✅ ${words.length} words seeded`);

  // Create word progress for the demo user
  for (const w of words) {
    const existingWord = await prisma.word.findUnique({
      where: { word: w.word },
    });
    if (existingWord) {
      await prisma.wordProgress.create({
        data: {
          userId: user.id,
          wordId: existingWord.id,
          mastery: 0,
          correct: 0,
          wrong: 0,
          reviewCount: 0,
        },
      });
    }
  }
  console.log(`✅ Word progress records created for all ${words.length} words`);

  // ===== Seed Sentences =====
  const sentencePatterns: Record<string, string[]> = {
    apple:       ['I see a red apple.', 'I like to eat an apple every day.', 'The apple is on the table.'],
    banana:      ['I see a yellow banana.', 'She is eating a banana.', 'The banana is very sweet.'],
    grape:       ['I see some purple grapes.', 'He bought a bunch of grapes.', 'The grapes are fresh.'],
    strawberry:  ['I see a red strawberry.', 'Strawberries are my favorite fruit.', 'She picked a strawberry.'],
    watermelon:  ['I see a big watermelon.', 'The watermelon is juicy and sweet.', 'We cut the watermelon in summer.'],
    pineapple:   ['I see a pineapple.', 'Pineapple tastes sweet and sour.', 'He is cutting a pineapple.'],
    mango:       ['I see a yellow mango.', 'Mango is a tropical fruit.', 'The mango is ripe.'],
    peach:       ['I see a pink peach.', 'The peach is soft and sweet.', 'I want to eat a peach.'],
    pear:        ['I see a green pear.', 'She gave me a juicy pear.', 'The pear tastes very good.'],
    lemon:       ['I see a yellow lemon.', 'Lemon is sour.', 'I drink lemon water in the morning.'],
    cherry:      ['I see some red cherries.', 'Cherries are small and sweet.', 'She likes cherry pie.'],
    blueberry:   ['I see some blueberries.', 'Blueberries are good for health.', 'I add blueberries to my yogurt.'],
    coconut:     ['I see a coconut.', 'Coconut water is refreshing.', 'He opened the coconut.'],
    avocado:     ['I see an avocado.', 'I like avocado toast for breakfast.', 'The avocado is creamy.'],
    apricot:     ['I see an apricot.', 'Apricots are small orange fruits.', 'The dried apricot is sweet.'],
    dog:         ['I see a cute dog.', 'The dog is running in the park.', 'My dog likes to play with me.'],
    cat:         ['I see a black cat.', 'The cat is sleeping on the sofa.', 'Her cat has green eyes.'],
    elephant:    ['I see a big elephant.', 'The elephant has a long trunk.', 'Elephants live in Africa and Asia.'],
    tiger:       ['I see a tiger.', 'The tiger is a strong animal.', 'Tigers have orange and black stripes.'],
    lion:        ['I see a lion.', 'The lion is the king of animals.', 'Lions live in groups.'],
    bear:        ['I see a brown bear.', 'The bear is looking for food.', 'Bears sleep in winter.'],
    rabbit:      ['I see a white rabbit.', 'The rabbit hops very fast.', 'My rabbit likes carrots.'],
    monkey:      ['I see a monkey.', 'The monkey is climbing a tree.', 'Monkeys are very smart.'],
    penguin:     ['I see a penguin.', 'Penguins live in cold places.', 'The penguin cannot fly.'],
    giraffe:     ['I see a giraffe.', 'The giraffe has a long neck.', 'Giraffes eat leaves from tall trees.'],
    dolphin:     ['I see a dolphin.', 'Dolphins swim in the ocean.', 'Dolphins are very friendly.'],
    butterfly:   ['I see a beautiful butterfly.', 'The butterfly has colorful wings.', 'A butterfly landed on the flower.'],
    squirrel:    ['I see a squirrel.', 'The squirrel is gathering nuts.', 'Squirrels live in trees.'],
    kangaroo:    ['I see a kangaroo.', 'The kangaroo can jump very far.', 'Kangaroos live in Australia.'],
    panda:       ['I see a panda.', 'The panda is eating bamboo.', 'Pandas are black and white.'],
    crimson:     ['I see a crimson flower.', 'The sky turned crimson at sunset.', 'She wore a crimson dress.'],
    turquoise:   ['I see a turquoise sea.', 'She wore a turquoise necklace.', 'The water is clear and turquoise.'],
    magenta:     ['I see a magenta flower.', 'Magenta is a bright color.', 'She painted the wall magenta.'],
    lavender:    ['I see lavender flowers.', 'Lavender smells very nice.', 'The field is full of lavender.'],
    coral:       ['I see a coral reef.', 'Coral is found in the ocean.', 'She likes coral color.'],
    olive:       ['I see an olive tree.', 'Olive oil is healthy.', 'She added olives to the salad.'],
    maroon:      ['I see a maroon car.', 'Maroon is a dark red color.', 'He wore a maroon jacket.'],
    beige:       ['I see a beige wall.', 'She bought a beige sofa.', 'The room is painted beige.'],
    ivory:       ['I see an ivory statue.', 'The ivory tower is beautiful.', 'She wore an ivory wedding dress.'],
    gold:        ['I see a gold ring.', 'She won a gold medal.', 'The sun is shining like gold.'],
    first:       ['I see the first star.', 'This is my first time here.', 'She is the first in line.'],
    second:      ['I see the second door.', 'Take the second left turn.', 'He is in second place.'],
    third:       ['I see the third floor.', 'This is my third try.', 'She sits in the third row.'],
    hundred:     ['I see a hundred flowers.', 'The book has a hundred pages.', 'A hundred people came.'],
    thousand:    ['I see a thousand stars.', 'It costs a thousand dollars.', 'A thousand birds flew by.'],
    million:     ['I see a million lights.', 'The city has a million people.', 'She won a million dollars.'],
    billion:     ['I see a billion stars.', 'The ocean has a billion fish.', 'A billion people live in cities.'],
    half:        ['I see the half moon.', 'I ate half of the cake.', 'Give me half please.'],
    quarter:     ['I see a quarter of the pie.', 'It is a quarter past three.', 'I found a quarter coin.'],
    double:      ['I see a double rainbow.', 'Double the amount please.', 'He ordered a double burger.'],
    parent:      ['I see a parent and child.', 'My parents love me very much.', 'She is a wonderful parent.'],
    son:         ['I see a son playing.', 'Her son is five years old.', 'The son helps his father.'],
    daughter:    ['I see a daughter smiling.', 'His daughter loves to draw.', 'The daughter hugs her mother.'],
    husband:     ['I see a husband and wife.', 'Her husband works in a hospital.', 'The husband cooks dinner.'],
    wife:        ['I see a happy wife.', 'His wife is a teacher.', 'The wife reads a book.'],
    grandparent: ['I see a grandparent.', 'My grandparents tell me stories.', 'The grandparent is very kind.'],
    grandson:    ['I see a grandson playing.', 'His grandson visits every Sunday.', 'The grandson is very smart.'],
    granddaughter: ['I see a granddaughter dancing.', 'Her granddaughter loves music.', 'The granddaughter sings beautifully.'],
    stepfather:  ['I see a stepfather.', 'Her stepfather is very supportive.', 'The stepfather drives them to school.'],
    inlaw:       ['I see my inlaw family.', 'She gets along with her inlaws.', 'The inlaw visit is fun.'],
    noodle:      ['I see a bowl of noodles.', 'I love eating hot noodles.', 'The noodle soup is delicious.'],
    soup:        ['I see a bowl of soup.', 'The chicken soup smells good.', 'I drink soup every evening.'],
    salad:       ['I see a green salad.', 'I ordered a salad for lunch.', 'The salad is fresh and healthy.'],
    pizza:       ['I see a pizza.', 'The pizza is hot and cheesy.', 'Let us share a pizza.'],
    burger:      ['I see a burger.', 'The burger comes with fries.', 'I want a burger for dinner.'],
    cake:        ['I see a chocolate cake.', 'The birthday cake has candles.', 'She baked a cake for the party.'],
    cookie:      ['I see a cookie jar.', 'Mom baked cookies for us.', 'The cookie is crunchy and sweet.'],
    cheese:      ['I see a piece of cheese.', 'Cheese is made from milk.', 'I like cheese on my sandwich.'],
    butter:      ['I see some butter.', 'Butter melts in the pan.', 'I spread butter on toast.'],
    coffee:      ['I see a cup of coffee.', 'I drink coffee every morning.', 'The coffee is hot and strong.'],
    juice:       ['I see a glass of juice.', 'Orange juice is my favorite.', 'Fresh juice is good for health.'],
    pasta:       ['I see a plate of pasta.', 'Pasta with tomato sauce is tasty.', 'She cooks pasta for dinner.'],
    steak:       ['I see a juicy steak.', 'The steak is cooked well.', 'He ordered a steak at the restaurant.'],
    pancake:     ['I see a stack of pancakes.', 'Pancakes with syrup are yummy.', 'We have pancakes for breakfast.'],
    sandwich:    ['I see a sandwich.', 'I made a chicken sandwich.', 'The sandwich is wrapped in paper.'],
    chocolate:   ['I see a bar of chocolate.', 'Chocolate makes me happy.', 'Dark chocolate is healthy.'],
    candy:       ['I see colorful candy.', 'Kids love candy on Halloween.', 'The candy is very sweet.'],
    honey:       ['I see a jar of honey.', 'Honey is made by bees.', 'I put honey in my tea.'],
    salt:        ['I see some salt.', 'Please pass me the salt.', 'Too much salt is not healthy.'],
    pepper:      ['I see black pepper.', 'Add some pepper to the soup.', 'Fresh pepper tastes better.'],
    time:        ['I see the time on the clock.', 'Time flies when you are happy.', 'What time is it now.'],
    day:         ['I see a sunny day.', 'Every day is a new start.', 'The day is bright and warm.'],
    night:       ['I see the night sky.', 'Good night, sweet dreams.', 'The stars shine at night.'],
    music:       ['I see music notes.', 'Music makes me feel happy.', 'I listen to music every day.'],
    happy:       ['I see a happy smile.', 'She looks very happy today.', 'Happy people spread joy.'],
    beautiful:   ['I see a beautiful flower.', 'The sunset is so beautiful.', 'You have a beautiful voice.'],
    important:   ['I see an important message.', 'Education is very important.', 'This document is important.'],
    different:   ['I see a different pattern.', 'Everyone is different in their own way.', 'Try a different approach.'],
    weather:     ['I see good weather today.', 'The weather is sunny and warm.', 'I check the weather every morning.'],
    work:        ['I see a lot of work.', 'He goes to work by bus.', 'Hard work leads to success.'],
    money:       ['I see some money on the table.', 'Money cannot buy happiness.', 'She saved money for a trip.'],
    city:        ['I see a big city.', 'The city lights shine at night.', 'I live near the city center.'],
    country:     ['I see a beautiful country.', 'China is a large country.', 'I want to visit another country.'],
    love:        ['I see love in their eyes.', 'Love makes the world go round.', 'I love my family.'],
    book:        ['I see a book on the shelf.', 'I read a book every week.', 'The book is very interesting.'],
    water:       ['I see clear water.', 'Water is essential for life.', 'I drink water every hour.'],
    friend:      ['I see my friend coming.', 'A good friend is a treasure.', 'I play with my friends after school.'],
    school:      ['I see a school bus.', 'I go to school every weekday.', 'The school is near my home.'],
    house:       ['I see a white house.', 'My house is cozy and warm.', 'They built a new house.'],
    dream:       ['I see a dream at night.', 'Follow your dream.', 'I have a dream to travel the world.'],
    // weather
    sunny:       ['I see a sunny sky.', 'It is a sunny day today.', 'The sunny weather makes me happy.'],
    rainy:       ['I see a rainy day.', 'It is rainy outside today.', 'I like the sound of rainy days.'],
    cloudy:      ['I see a cloudy sky.', 'The sky is cloudy this morning.', 'Cloudy days are good for reading.'],
    windy:       ['I see a windy day.', 'It is very windy at the beach.', 'The windy breeze feels nice.'],
    snowy:       ['I see a snowy mountain.', 'The snowy landscape is beautiful.', 'I love snowy winter days.'],
    storm:       ['I see a big storm.', 'The storm is coming soon.', 'We stayed inside during the storm.'],
    fog:         ['I see thick fog.', 'The fog covers the road.', 'Drive carefully in the fog.'],
    rainbow:     ['I see a rainbow.', 'A rainbow appeared after the rain.', 'The rainbow has seven colors.'],
    lightning:   ['I see lightning in the sky.', 'Lightning is very bright.', 'The lightning struck the tree.'],
    temperature: ['I see the temperature is high.', 'The temperature drops at night.', 'Check the temperature before going out.'],
    // mood
    sad:         ['I see a sad face.', 'She looks sad today.', 'It is okay to feel sad sometimes.'],
    angry:       ['I see an angry man.', 'He is angry about the news.', 'Do not get angry over small things.'],
    excited:     ['I see excited children.', 'She is excited about the trip.', 'Everyone is excited for the party.'],
    nervous:     ['I see a nervous student.', 'I feel nervous before speaking.', 'She was nervous on the first day.'],
    calm:        ['I see a calm lake.', 'Stay calm and think clearly.', 'He is always calm under pressure.'],
    bored:       ['I see a bored cat.', 'The bored child looked for a toy.', 'I get bored when there is nothing to do.'],
    proud:       ['I see a proud mother.', 'He is proud of his work.', 'I am very proud of you.'],
    afraid:      ['I see an afraid child.', 'She is afraid of spiders.', 'Do not be afraid to try new things.'],
    surprised:   ['I see a surprised look.', 'She was surprised by the news.', 'I am surprised you came so early.'],
    // sport
    run:         ['I see people run in the park.', 'I run every morning.', 'Let us run together.'],
    swim:        ['I see fish swim in the water.', 'She can swim very well.', 'I like to swim in summer.'],
    jump:        ['I see a rabbit jump.', 'The boy can jump high.', 'Jump up and down five times.'],
    basketball:  ['I see a basketball game.', 'He plays basketball after school.', 'The basketball team won the match.'],
    football:    ['I see a football field.', 'Football is fun to play.', 'They are watching a football match.'],
    tennis:      ['I see a tennis court.', 'She enjoys playing tennis.', 'The tennis player served the ball.'],
    cycling:     ['I see a cycling path.', 'Cycling is great exercise.', 'I go cycling with my friends.'],
    skiing:      ['I see a skiing slope.', 'Skiing down the mountain is thrilling.', 'They are learning how to ski.'],
    exercise:    ['I see people exercise outside.', 'Daily exercise is important.', 'I do morning exercise every day.'],
    match:       ['I see an exciting match.', 'The match was very close.', 'Who won the match yesterday.'],
  };

  for (const w of words) {
    const key = w.word.toLowerCase();
    const existingWord = await prisma.word.findUnique({ where: { word: w.word } });
    if (existingWord && sentencePatterns[key]) {
      const sentences = sentencePatterns[key].map((text, idx) => ({
        wordId: existingWord.id,
        text,
        translation: '',
        level: idx + 1,
      }));
      await prisma.sentence.createMany({ data: sentences });
    }
  }
  console.log('✅ Sentences seeded for all words');

  console.log('🎉 Database seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
