import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const words = [
  // ===== FRUIT (15) =====
  { word: 'apple', phonetic: '/ˈæp.əl/', meaning: '苹果', category: 'fruit', difficulty: 'easy', level: 1 },
  { word: 'banana', phonetic: '/bəˈnæn.ə/', meaning: '香蕉', category: 'fruit', difficulty: 'easy', level: 1 },
  { word: 'grape', phonetic: '/ɡreɪp/', meaning: '葡萄', category: 'fruit', difficulty: 'easy', level: 1 },
  { word: 'strawberry', phonetic: '/ˈstrɔː.bər.i/', meaning: '草莓', category: 'fruit', difficulty: 'medium', level: 3 },
  { word: 'watermelon', phonetic: '/ˈwɔː.tər.mel.ən/', meaning: '西瓜', category: 'fruit', difficulty: 'medium', level: 3 },
  { word: 'pineapple', phonetic: '/ˈpaɪn.æp.əl/', meaning: '菠萝', category: 'fruit', difficulty: 'medium', level: 3 },
  { word: 'mango', phonetic: '/ˈmæŋ.ɡoʊ/', meaning: '芒果', category: 'fruit', difficulty: 'easy', level: 2 },
  { word: 'peach', phonetic: '/piːtʃ/', meaning: '桃子', category: 'fruit', difficulty: 'easy', level: 1 },
  { word: 'pear', phonetic: '/per/', meaning: '梨', category: 'fruit', difficulty: 'easy', level: 1 },
  { word: 'lemon', phonetic: '/ˈlem.ən/', meaning: '柠檬', category: 'fruit', difficulty: 'easy', level: 2 },
  { word: 'cherry', phonetic: '/ˈtʃer.i/', meaning: '樱桃', category: 'fruit', difficulty: 'easy', level: 2 },
  { word: 'blueberry', phonetic: '/ˈbluː.be.ri/', meaning: '蓝莓', category: 'fruit', difficulty: 'medium', level: 3 },
  { word: 'coconut', phonetic: '/ˈkoʊ.kə.nʌt/', meaning: '椰子', category: 'fruit', difficulty: 'medium', level: 2 },
  { word: 'avocado', phonetic: '/ˌæv.əˈkɑː.doʊ/', meaning: '牛油果', category: 'fruit', difficulty: 'hard', level: 5 },
  { word: 'apricot', phonetic: '/əˈprɒt/', meaning: '杏子', category: 'fruit', difficulty: 'hard', level: 5 },

  // ===== ANIMAL (15) =====
  { word: 'dog', phonetic: '/dɔːɡ/', meaning: '狗', category: 'animal', difficulty: 'easy', level: 1 },
  { word: 'cat', phonetic: '/kæt/', meaning: '猫', category: 'animal', difficulty: 'easy', level: 1 },
  { word: 'elephant', phonetic: '/ˈel.ɪ.fənt/', meaning: '大象', category: 'animal', difficulty: 'medium', level: 3 },
  { word: 'tiger', phonetic: '/ˈtaɪ.ɡər/', meaning: '老虎', category: 'animal', difficulty: 'easy', level: 2 },
  { word: 'lion', phonetic: '/ˈlaɪ.ən/', meaning: '狮子', category: 'animal', difficulty: 'easy', level: 2 },
  { word: 'bear', phonetic: '/ber/', meaning: '熊', category: 'animal', difficulty: 'easy', level: 1 },
  { word: 'rabbit', phonetic: '/ˈræb.ɪt/', meaning: '兔子', category: 'animal', difficulty: 'easy', level: 2 },
  { word: 'monkey', phonetic: '/ˈmʌŋ.ki/', meaning: '猴子', category: 'animal', difficulty: 'easy', level: 2 },
  { word: 'penguin', phonetic: '/ˈpeŋ.ɡwɪn/', meaning: '企鹅', category: 'animal', difficulty: 'medium', level: 3 },
  { word: 'giraffe', phonetic: '/dʒəˈræf/', meaning: '长颈鹿', category: 'animal', difficulty: 'medium', level: 3 },
  { word: 'dolphin', phonetic: '/ˈdɒl.fɪn/', meaning: '海豚', category: 'animal', difficulty: 'medium', level: 3 },
  { word: 'butterfly', phonetic: '/ˈbʌt.ər.flaɪ/', meaning: '蝴蝶', category: 'animal', difficulty: 'medium', level: 4 },
  { word: 'squirrel', phonetic: '/ˈskwɜːr.əl/', meaning: '松鼠', category: 'animal', difficulty: 'hard', level: 4 },
  { word: 'kangaroo', phonetic: '/ˌkæŋ.ɡəˈruː/', meaning: '袋鼠', category: 'animal', difficulty: 'hard', level: 4 },
  { word: 'panda', phonetic: '/ˈpæn.də/', meaning: '熊猫', category: 'animal', difficulty: 'easy', level: 1 },

  // ===== COLOR (10) =====
  { word: 'crimson', phonetic: '/ˈkrɪm.zən/', meaning: '深红色', category: 'color', difficulty: 'hard', level: 5 },
  { word: 'turquoise', phonetic: '/ˈtɜːr.kwɔːz/', meaning: '绿松石色', category: 'color', difficulty: 'hard', level: 5 },
  { word: 'magenta', phonetic: '/məˈdzen.tə/', meaning: '品红色', category: 'color', difficulty: 'hard', level: 5 },
  { word: 'lavender', phonetic: '/ˈlæv.ən.dər/', meaning: '淡紫色', category: 'color', difficulty: 'medium', level: 4 },
  { word: 'coral', phonetic: '/ˈkɔːr.əl/', meaning: '珊瑚色', category: 'color', difficulty: 'medium', level: 3 },
  { word: 'olive', phonetic: '/ˈɒl.ɪv/', meaning: '橄榄绿', category: 'color', difficulty: 'medium', level: 3 },
  { word: 'maroon', phonetic: '/məˈruːn/', meaning: '栗色', category: 'color', difficulty: 'medium', level: 3 },
  { word: 'beige', phonetic: '/beɪʒ/', meaning: '米色', category: 'color', difficulty: 'medium', level: 3 },
  { word: 'ivory', phonetic: '/ˈaɪ.vər.i/', meaning: '象牙白', category: 'color', difficulty: 'medium', level: 4 },
  { word: 'gold', phonetic: '/ɡoʊld/', meaning: '金色', category: 'color', difficulty: 'easy', level: 2 },

  // ===== NUMBER (10) =====
  { word: 'first', phonetic: '/fɜːrst/', meaning: '第一', category: 'number', difficulty: 'easy', level: 2 },
  { word: 'second', phonetic: '/ˈsek.ənd/', meaning: '第二', category: 'number', difficulty: 'easy', level: 2 },
  { word: 'third', phonetic: '/θɜːrd/', meaning: '第三', category: 'number', difficulty: 'easy', level: 2 },
  { word: 'hundred', phonetic: '/ˈhʌn.drəd/', meaning: '百', category: 'number', difficulty: 'easy', level: 2 },
  { word: 'thousand', phonetic: '/ˈθaʊ.zənd/', meaning: '千', category: 'number', difficulty: 'easy', level: 2 },
  { word: 'million', phonetic: '/ˈmɪl.jən/', meaning: '百万', category: 'number', difficulty: 'medium', level: 3 },
  { word: 'billion', phonetic: '/ˈbɪl.jən/', meaning: '十亿', category: 'number', difficulty: 'medium', level: 3 },
  { word: 'half', phonetic: '/hæf/', meaning: '一半', category: 'number', difficulty: 'easy', level: 1 },
  { word: 'quarter', phonetic: '/ˈkwɔːr.t̬ɚ/', meaning: '四分之一', category: 'number', difficulty: 'medium', level: 3 },
  { word: 'double', phonetic: '/ˈdʌb.əl/', meaning: '双倍', category: 'number', difficulty: 'easy', level: 2 },

  // ===== FAMILY (10) =====
  { word: 'parent', phonetic: '/ˈper.ənt/', meaning: '父母', category: 'family', difficulty: 'easy', level: 2 },
  { word: 'son', phonetic: '/sʌn/', meaning: '儿子', category: 'family', difficulty: 'easy', level: 1 },
  { word: 'daughter', phonetic: '/ˈdɔːt̬.ər/', meaning: '女儿', category: 'family', difficulty: 'easy', level: 1 },
  { word: 'husband', phonetic: '/ˈhʌz.bənd/', meaning: '丈夫', category: 'family', difficulty: 'easy', level: 2 },
  { word: 'wife', phonetic: '/waɪf/', meaning: '妻子', category: 'family', difficulty: 'easy', level: 1 },
  { word: 'grandparent', phonetic: '/ˈɡræn.per.ənt/', meaning: '祖父母', category: 'family', difficulty: 'medium', level: 3 },
  { word: 'grandson', phonetic: '/ˈɡræn.sʌn/', meaning: '孙子', category: 'family', difficulty: 'medium', level: 3 },
  { word: 'granddaughter', phonetic: '/ˌɡrænˈdɔːt̬.ər/', meaning: '孙女', category: 'family', difficulty: 'hard', level: 4 },
  { word: 'stepfather', phonetic: '/ˈstep.fɑː.ðər/', meaning: '继父', category: 'family', difficulty: 'hard', level: 4 },
  { word: 'inlaw', phonetic: '/ˈɪnˌlɔː/', meaning: '姻亲', category: 'family', difficulty: 'hard', level: 5 },

  // ===== FOOD (20) =====
  { word: 'noodle', phonetic: '/ˈnuː.dəl/', meaning: '面条', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'soup', phonetic: '/suːp/', meaning: '汤', category: 'food', difficulty: 'easy', level: 1 },
  { word: 'salad', phonetic: '/ˈsæl.əd/', meaning: '沙拉', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'pizza', phonetic: '/ˈpiːt.sə/', meaning: '披萨', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'burger', phonetic: '/ˈbɜːr.ɡər/', meaning: '汉堡', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'cake', phonetic: '/keɪk/', meaning: '蛋糕', category: 'food', difficulty: 'easy', level: 1 },
  { word: 'cookie', phonetic: '/ˈkʊk.i/', meaning: '饼干', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'cheese', phonetic: '/tʃiːz/', meaning: '奶酪', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'butter', phonetic: '/ˈbʌt.ər/', meaning: '黄油', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'coffee', phonetic: '/ˈkɒf.i/', meaning: '咖啡', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'juice', phonetic: '/dʒuːs/', meaning: '果汁', category: 'food', difficulty: 'easy', level: 1 },
  { word: 'pasta', phonetic: '/ˈpæs.tə/', meaning: '意大利面', category: 'food', difficulty: 'medium', level: 3 },
  { word: 'steak', phonetic: '/steɪk/', meaning: '牛排', category: 'food', difficulty: 'medium', level: 3 },
  { word: 'pancake', phonetic: '/ˈpæn.keɪk/', meaning: '煎饼', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'sandwich', phonetic: '/ˈsæn.wɪtʃ/', meaning: '三明治', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'chocolate', phonetic: '/ˈtʃɒk.lət/', meaning: '巧克力', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'candy', phonetic: '/ˈkæn.di/', meaning: '糖果', category: 'food', difficulty: 'easy', level: 1 },
  { word: 'honey', phonetic: '/ˈhʌn.i/', meaning: '蜂蜜', category: 'food', difficulty: 'easy', level: 2 },
  { word: 'salt', phonetic: '/sɔːlt/', meaning: '盐', category: 'food', difficulty: 'easy', level: 1 },
  { word: 'pepper', phonetic: '/ˈpep.ər/', meaning: '胡椒', category: 'food', difficulty: 'easy', level: 2 },

  // ===== GENERAL (20) =====
  { word: 'time', phonetic: '/taɪm/', meaning: '时间', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'day', phonetic: '/deɪ/', meaning: '天', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'night', phonetic: '/naɪt/', meaning: '夜晚', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'music', phonetic: '/ˈmjuː.zɪk/', meaning: '音乐', category: 'general', difficulty: 'easy', level: 2 },
  { word: 'beautiful', phonetic: '/ˈbjuː.tɪ.fəl/', meaning: '美丽的', category: 'general', difficulty: 'medium', level: 3 },
  { word: 'important', phonetic: '/ɪmˈpɔːr.tənt/', meaning: '重要的', category: 'general', difficulty: 'medium', level: 3 },
  { word: 'different', phonetic: '/ˈdɪf.ər.ənt/', meaning: '不同的', category: 'general', difficulty: 'medium', level: 3 },
  { word: 'work', phonetic: '/wɜːrk/', meaning: '工作', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'money', phonetic: '/ˈmʌn.i/', meaning: '钱', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'city', phonetic: '/ˈsɪt.i/', meaning: '城市', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'country', phonetic: '/ˈkʌn.tri/', meaning: '国家', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'love', phonetic: '/lʌv/', meaning: '爱', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'book', phonetic: '/bʊk/', meaning: '书', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'water', phonetic: '/ˈwɔː.tər/', meaning: '水', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'friend', phonetic: '/frend/', meaning: '朋友', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'school', phonetic: '/skuːl/', meaning: '学校', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'house', phonetic: '/haʊs/', meaning: '房子', category: 'general', difficulty: 'easy', level: 1 },
  { word: 'dream', phonetic: '/driːm/', meaning: '梦想', category: 'general', difficulty: 'easy', level: 2 },

  // ===== WEATHER (10) =====
  { word: 'sunny', phonetic: '/ˈsʌn.i/', meaning: '晴朗的', category: 'weather', difficulty: 'easy', level: 1 },
  { word: 'rainy', phonetic: '/ˈreɪ.ni/', meaning: '下雨的', category: 'weather', difficulty: 'easy', level: 1 },
  { word: 'cloudy', phonetic: '/ˈklaʊ.di/', meaning: '多云的', category: 'weather', difficulty: 'easy', level: 1 },
  { word: 'windy', phonetic: '/ˈwɪn.di/', meaning: '有风的', category: 'weather', difficulty: 'easy', level: 2 },
  { word: 'snowy', phonetic: '/ˈsnoʊ.i/', meaning: '下雪的', category: 'weather', difficulty: 'easy', level: 2 },
  { word: 'storm', phonetic: '/stɔːrm/', meaning: '暴风雨', category: 'weather', difficulty: 'medium', level: 3 },
  { word: 'fog', phonetic: '/fɒɡ/', meaning: '雾', category: 'weather', difficulty: 'easy', level: 2 },
  { word: 'rainbow', phonetic: '/ˈreɪn.boʊ/', meaning: '彩虹', category: 'weather', difficulty: 'medium', level: 3 },
  { word: 'lightning', phonetic: '/ˈlaɪt.nɪŋ/', meaning: '闪电', category: 'weather', difficulty: 'hard', level: 4 },
  { word: 'temperature', phonetic: '/ˈtem.pər.ə.tʃər/', meaning: '温度', category: 'weather', difficulty: 'hard', level: 4 },

  // ===== MOOD (10) =====
  { word: 'happy', phonetic: '/ˈhæp.i/', meaning: '快乐的', category: 'mood', difficulty: 'easy', level: 1 },
  { word: 'sad', phonetic: '/sæd/', meaning: '悲伤的', category: 'mood', difficulty: 'easy', level: 1 },
  { word: 'angry', phonetic: '/ˈæŋ.ɡri/', meaning: '生气的', category: 'mood', difficulty: 'easy', level: 1 },
  { word: 'excited', phonetic: '/ɪkˈsaɪ.tɪd/', meaning: '兴奋的', category: 'mood', difficulty: 'medium', level: 3 },
  { word: 'nervous', phonetic: '/ˈnɜːr.vəs/', meaning: '紧张的', category: 'mood', difficulty: 'medium', level: 3 },
  { word: 'calm', phonetic: '/kɑːm/', meaning: '平静的', category: 'mood', difficulty: 'easy', level: 2 },
  { word: 'bored', phonetic: '/bɔːrd/', meaning: '无聊的', category: 'mood', difficulty: 'easy', level: 2 },
  { word: 'proud', phonetic: '/praʊd/', meaning: '自豪的', category: 'mood', difficulty: 'medium', level: 3 },
  { word: 'afraid', phonetic: '/əˈfreɪd/', meaning: '害怕的', category: 'mood', difficulty: 'easy', level: 2 },
  { word: 'surprised', phonetic: '/sərˈpraɪzd/', meaning: '惊讶的', category: 'mood', difficulty: 'medium', level: 4 },

  // ===== SPORT (10) =====
  { word: 'run', phonetic: '/rʌn/', meaning: '跑步', category: 'sport', difficulty: 'easy', level: 1 },
  { word: 'swim', phonetic: '/swɪm/', meaning: '游泳', category: 'sport', difficulty: 'easy', level: 1 },
  { word: 'jump', phonetic: '/dʒʌmp/', meaning: '跳跃', category: 'sport', difficulty: 'easy', level: 1 },
  { word: 'basketball', phonetic: '/ˈbæs.kɪt.bɔːl/', meaning: '篮球', category: 'sport', difficulty: 'medium', level: 3 },
  { word: 'football', phonetic: '/ˈfʊt.bɔːl/', meaning: '足球', category: 'sport', difficulty: 'easy', level: 2 },
  { word: 'tennis', phonetic: '/ˈten.ɪs/', meaning: '网球', category: 'sport', difficulty: 'medium', level: 3 },
  { word: 'cycling', phonetic: '/ˈsaɪ.klɪŋ/', meaning: '骑行', category: 'sport', difficulty: 'medium', level: 3 },
  { word: 'skiing', phonetic: '/ˈskiː.ɪŋ/', meaning: '滑雪', category: 'sport', difficulty: 'medium', level: 4 },
  { word: 'exercise', phonetic: '/ˈek.sər.saɪz/', meaning: '锻炼', category: 'sport', difficulty: 'medium', level: 4 },
  { word: 'match', phonetic: '/mætʃ/', meaning: '比赛', category: 'sport', difficulty: 'easy', level: 2 },
];

const exampleSentences: Record<string, string> = {
  apple: 'I eat an apple every day for a healthy lifestyle.',
  banana: 'Bananas are rich in potassium and very delicious.',
  grape: 'She picked some purple grapes from the vine.',
  strawberry: 'Strawberries with cream are my favorite dessert.',
  watermelon: 'Watermelon is the perfect summer fruit.',
  pineapple: 'Pineapple goes great on pizza.',
  mango: 'Mango smoothies are so refreshing.',
  peach: 'The ripe peach is soft and sweet.',
  pear: 'I bought a bag of pears at the market.',
  lemon: 'Add some lemon juice to your water.',
  cherry: 'Cherry blossoms bloom in spring.',
  blueberry: 'Blueberries are packed with antioxidants.',
  coconut: 'Coconut water is very hydrating.',
  avocado: 'Avocado toast is popular among young people.',
  apricot: 'Apricots are small orange fruits.',
  dog: 'My dog loves to play fetch in the park.',
  cat: 'The cat is sleeping peacefully on the sofa.',
  elephant: 'Elephants are the largest land animals on Earth.',
  tiger: 'Tigers are powerful and majestic creatures.',
  lion: 'The lion is known as the king of the jungle.',
  bear: 'Bears hibernate during the cold winter months.',
  rabbit: 'The rabbit hops quickly across the meadow.',
  monkey: 'Monkeys love to swing from tree to tree.',
  penguin: 'Penguins cannot fly but they are excellent swimmers.',
  giraffe: 'Giraffes have the longest necks of any animal.',
  dolphin: 'Dolphins are among the smartest animals in the ocean.',
  butterfly: 'A beautiful butterfly landed on the flower.',
  squirrel: 'The squirrel gathered nuts for the winter.',
  kangaroo: 'Kangaroos carry their babies in a pouch.',
  panda: 'Pandas spend most of their day eating bamboo.',
  crimson: 'The crimson sunset painted the sky in brilliant colors.',
  turquoise: 'She wore a stunning turquoise necklace.',
  magenta: 'The magenta flowers stood out against the green leaves.',
  lavender: 'The field of lavender smelled wonderful.',
  coral: 'Coral reefs are home to many sea creatures.',
  olive: 'Olive oil is healthy and delicious.',
  maroon: 'He drove a maroon-colored car.',
  beige: 'The walls were painted a soft beige color.',
  ivory: 'The ivory wedding dress looked elegant.',
  gold: 'She received a gold medal for her achievement.',
  first: 'This is my first time visiting Beijing.',
  second: 'Take the second turn on the left.',
  third: 'He finished in third place in the race.',
  hundred: 'The book has over a hundred pages.',
  thousand: 'A thousand stars shone brightly in the sky.',
  million: 'One million people attended the concert.',
  billion: 'The company is worth several billion dollars.',
  half: 'Cut the cake in half, please.',
  quarter: 'I\'d like a quarter pound of beef.',
  double: 'Double the recipe for a bigger batch.',
  parent: 'Every parent wants the best for their child.',
  son: 'Her son just started kindergarten.',
  daughter: 'His daughter won the art competition.',
  husband: 'She introduced her husband to her colleagues.',
  wife: 'The couple has been married for twenty years.',
  grandparent: 'My grandparents tell the best stories.',
  grandson: 'His grandson visits him every weekend.',
  granddaughter: 'She dotes on her granddaughter.',
  stepfather: 'Her stepfather supported her dreams.',
  inlaw: 'I am meeting my inlaws for dinner tonight.',
  noodle: 'I love eating hot noodles in winter.',
  soup: 'Mom made chicken soup for me.',
  salad: 'I ordered a garden salad for lunch.',
  pizza: 'Let\'s order a pepperoni pizza tonight.',
  burger: 'I\'ll have a cheeseburger with fries.',
  cake: 'We celebrated with a chocolate birthday cake.',
  cookie: 'Mom baked chocolate chip cookies.',
  cheese: 'I love melted cheese on toast.',
  butter: 'Add some butter to the pan.',
  coffee: 'I need my morning cup of coffee.',
  juice: 'Fresh orange juice is the best.',
  pasta: 'Spaghetti is my favorite Italian pasta.',
  steak: 'The steak was cooked to perfection.',
  pancake: 'Fluffy pancakes with maple syrup!',
  sandwich: 'I made a turkey sandwich for lunch.',
  chocolate: 'Dark chocolate is healthier than milk chocolate.',
  candy: 'Children love candy on Halloween.',
  honey: 'Honey is a natural sweetener.',
  salt: 'Please pass me the salt.',
  pepper: 'Add some black pepper to taste.',
  time: 'Time flies when you are having fun.',
  day: 'What a beautiful sunny day!',
  night: 'Good night, sleep well.',
  music: 'I enjoy listening to classical music.',
  happy: 'She looks very happy today.',
  beautiful: 'The sunset was absolutely beautiful.',
  important: 'Education is very important for everyone.',
  different: 'They have different opinions on the matter.',
  weather: 'The weather is nice today for a walk.',
  work: 'He goes to work by bus every day.',
  money: 'Money cannot buy happiness.',
  city: 'New York is a vibrant and exciting city.',
  country: 'China is a large and diverse country.',
  love: 'Love makes the world go round.',
  book: 'I am reading an interesting book right now.',
  water: 'Please give me a glass of water.',
  friend: 'She is my best friend since childhood.',
  school: 'The children go to school every weekday.',
  house: 'They live in a cozy little house.',
  dream: 'Never give up on your dreams.',
  // weather
  sunny: 'It is a bright and sunny day today.',
  rainy: 'Take an umbrella because it is rainy outside.',
  cloudy: 'The sky is very cloudy this morning.',
  windy: 'It is too windy to fly a kite safely.',
  snowy: 'The mountain looks beautiful when it is snowy.',
  storm: 'A big storm is coming from the ocean.',
  fog: 'The fog is so thick I cannot see the road.',
  rainbow: 'After the rain, a beautiful rainbow appeared.',
  lightning: 'The lightning lit up the whole sky.',
  temperature: 'The temperature today is very high.',
  // mood
  sad: 'She felt sad when her friend moved away.',
  angry: 'He was angry because he lost his keys.',
  excited: 'The children are excited about the field trip.',
  nervous: 'I always feel nervous before an exam.',
  calm: 'Take a deep breath and stay calm.',
  bored: 'He was bored during the long meeting.',
  proud: 'Her parents are very proud of her success.',
  afraid: 'She is afraid of the dark.',
  surprised: 'I was surprised by the birthday gift.',
  // sport
  run: 'I run every morning to stay healthy.',
  swim: 'She can swim across the pool very fast.',
  jump: 'The cat can jump over the fence.',
  basketball: 'He plays basketball with his friends after school.',
  football: 'Football is the most popular sport in the world.',
  tennis: 'She won the tennis match yesterday.',
  cycling: 'Cycling is a fun way to explore the city.',
  skiing: 'We go skiing in the mountains every winter.',
  exercise: 'Regular exercise keeps your body strong.',
  match: 'The football match starts at three o\'clock.',
};

async function main() {
  console.log('🌱 Seeding database with 100 words...');

  // Create a default user
  const user = await prisma.user.upsert({
    where: { username: 'demo_user' },
    update: {},
    create: {
      username: 'demo_user',
      streak: 0,
      totalXP: 0,
    },
  });
  console.log('✅ Default user created:', user.username);

  // Create words
  for (const w of words) {
    const key = w.word.toLowerCase();
    await prisma.word.create({
      data: {
        ...w,
        example: exampleSentences[key] || `This is an example sentence with "${w.word}".`,
      },
    });
  }
  console.log(`✅ ${words.length} words seeded`);

  // Create word progress for the demo user
  for (const w of words) {
    const existingWord = await prisma.word.findUnique({
      where: { word: w.word },
    });
    if (existingWord) {
      await prisma.wordProgress.create({
        data: {
          userId: user.id,
          wordId: existingWord.id,
          mastery: 0,
          correct: 0,
          wrong: 0,
          reviewCount: 0,
        },
      });
    }
  }
  console.log(`✅ Word progress records created for all ${words.length} words`);

  // ===== Seed Sentences =====
  const sentencePatterns: Record<string, Array<{ text: string; translation: string }>> = {
    apple: [{ text: 'I see a red apple.', translation: '我看到一个红苹果。' }, { text: 'I like to eat an apple every day.', translation: '我喜欢每天吃一个苹果。' }, { text: 'The apple is on the table.', translation: '苹果在桌子上。' }],
    banana: [{ text: 'I see a yellow banana.', translation: '我看到一根黄香蕉。' }, { text: 'She is eating a banana.', translation: '她正在吃香蕉。' }, { text: 'The banana is very sweet.', translation: '这香蕉很甜。' }],
    grape: [{ text: 'I see some purple grapes.', translation: '我看到一些紫葡萄。' }, { text: 'He bought a bunch of grapes.', translation: '他买了一串葡萄。' }, { text: 'The grapes are fresh.', translation: '葡萄很新鲜。' }],
    strawberry: [{ text: 'I see a red strawberry.', translation: '我看到一颗红草莓。' }, { text: 'Strawberries are my favorite fruit.', translation: '草莓是我最喜欢的水果。' }, { text: 'She picked a strawberry.', translation: '她摘了一颗草莓。' }],
    watermelon: [{ text: 'I see a big watermelon.', translation: '我看到一个大西瓜。' }, { text: 'The watermelon is juicy and sweet.', translation: '西瓜多汁又甜。' }, { text: 'We cut the watermelon in summer.', translation: '我们夏天切西瓜。' }],
    pineapple: [{ text: 'I see a pineapple.', translation: '我看到一个菠萝。' }, { text: 'Pineapple tastes sweet and sour.', translation: '菠萝尝起来酸甜。' }, { text: 'He is cutting a pineapple.', translation: '他正在切菠萝。' }],
    mango: [{ text: 'I see a yellow mango.', translation: '我看到一个黄芒果。' }, { text: 'Mango is a tropical fruit.', translation: '芒果是热带水果。' }, { text: 'The mango is ripe.', translation: '芒果熟了。' }],
    peach: [{ text: 'I see a pink peach.', translation: '我看到一个粉色的桃子。' }, { text: 'The peach is soft and sweet.', translation: '桃子又软又甜。' }, { text: 'I want to eat a peach.', translation: '我想吃桃子。' }],
    pear: [{ text: 'I see a green pear.', translation: '我看到一个绿梨。' }, { text: 'She gave me a juicy pear.', translation: '她给了我一个多汁的梨。' }, { text: 'The pear tastes very good.', translation: '梨的味道很好。' }],
    lemon: [{ text: 'I see a yellow lemon.', translation: '我看到一个黄柠檬。' }, { text: 'Lemon is sour.', translation: '柠檬是酸的。' }, { text: 'I drink lemon water in the morning.', translation: '我早上喝柠檬水。' }],
    cherry: [{ text: 'I see some red cherries.', translation: '我看到一些红樱桃。' }, { text: 'Cherries are small and sweet.', translation: '樱桃又小又甜。' }, { text: 'She likes cherry pie.', translation: '她喜欢樱桃派。' }],
    blueberry: [{ text: 'I see some blueberries.', translation: '我看到一些蓝莓。' }, { text: 'Blueberries are good for health.', translation: '蓝莓对健康有益。' }, { text: 'I add blueberries to my yogurt.', translation: '我在酸奶里加蓝莓。' }],
    coconut: [{ text: 'I see a coconut.', translation: '我看到一个椰子。' }, { text: 'Coconut water is refreshing.', translation: '椰子水很清爽。' }, { text: 'He opened the coconut.', translation: '他打开了椰子。' }],
    avocado: [{ text: 'I see an avocado.', translation: '我看到一个牛油果。' }, { text: 'I like avocado toast for breakfast.', translation: '我早餐喜欢牛油果吐司。' }, { text: 'The avocado is creamy.', translation: '牛油果很绵密。' }],
    apricot: [{ text: 'I see an apricot.', translation: '我看到一个杏子。' }, { text: 'Apricots are small orange fruits.', translation: '杏子是橙色的小水果。' }, { text: 'The dried apricot is sweet.', translation: '杏干很甜。' }],
    dog: [{ text: 'I see a cute dog.', translation: '我看到一只可爱的狗。' }, { text: 'The dog is running in the park.', translation: '狗在公园里跑。' }, { text: 'My dog likes to play with me.', translation: '我的狗喜欢和我玩。' }],
    cat: [{ text: 'I see a black cat.', translation: '我看到一只黑猫。' }, { text: 'The cat is sleeping on the sofa.', translation: '猫在沙发上睡觉。' }, { text: 'Her cat has green eyes.', translation: '她的猫有绿色的眼睛。' }],
    elephant: [{ text: 'I see a big elephant.', translation: '我看到一头大象。' }, { text: 'The elephant has a long trunk.', translation: '大象有长长的鼻子。' }, { text: 'Elephants live in Africa and Asia.', translation: '大象生活在非洲和亚洲。' }],
    tiger: [{ text: 'I see a tiger.', translation: '我看到一只老虎。' }, { text: 'The tiger is a strong animal.', translation: '老虎是强壮的动物。' }, { text: 'Tigers have orange and black stripes.', translation: '老虎有橙色和黑色的条纹。' }],
    lion: [{ text: 'I see a lion.', translation: '我看到一头狮子。' }, { text: 'The lion is the king of animals.', translation: '狮子是百兽之王。' }, { text: 'Lions live in groups.', translation: '狮子群居生活。' }],
    bear: [{ text: 'I see a brown bear.', translation: '我看到一只棕熊。' }, { text: 'The bear is looking for food.', translation: '熊在找食物。' }, { text: 'Bears sleep in winter.', translation: '熊在冬天睡觉。' }],
    rabbit: [{ text: 'I see a white rabbit.', translation: '我看到一只白兔。' }, { text: 'The rabbit hops very fast.', translation: '兔子跳得很快。' }, { text: 'My rabbit likes carrots.', translation: '我的兔子喜欢胡萝卜。' }],
    monkey: [{ text: 'I see a monkey.', translation: '我看到一只猴子。' }, { text: 'The monkey is climbing a tree.', translation: '猴子在爬树。' }, { text: 'Monkeys are very smart.', translation: '猴子非常聪明。' }],
    penguin: [{ text: 'I see a penguin.', translation: '我看到一只企鹅。' }, { text: 'Penguins live in cold places.', translation: '企鹅生活在寒冷的地方。' }, { text: 'The penguin cannot fly.', translation: '企鹅不会飞。' }],
    giraffe: [{ text: 'I see a giraffe.', translation: '我看到一只长颈鹿。' }, { text: 'The giraffe has a long neck.', translation: '长颈鹿有长长的脖子。' }, { text: 'Giraffes eat leaves from tall trees.', translation: '长颈鹿吃高树上的叶子。' }],
    dolphin: [{ text: 'I see a dolphin.', translation: '我看到一只海豚。' }, { text: 'Dolphins swim in the ocean.', translation: '海豚在大海里游泳。' }, { text: 'Dolphins are very friendly.', translation: '海豚非常友好。' }],
    butterfly: [{ text: 'I see a beautiful butterfly.', translation: '我看到一只美丽的蝴蝶。' }, { text: 'The butterfly has colorful wings.', translation: '蝴蝶有彩色的翅膀。' }, { text: 'A butterfly landed on the flower.', translation: '一只蝴蝶落在花上。' }],
    squirrel: [{ text: 'I see a squirrel.', translation: '我看到一只松鼠。' }, { text: 'The squirrel is gathering nuts.', translation: '松鼠在收集坚果。' }, { text: 'Squirrels live in trees.', translation: '松鼠住在树上。' }],
    kangaroo: [{ text: 'I see a kangaroo.', translation: '我看到一只袋鼠。' }, { text: 'The kangaroo can jump very far.', translation: '袋鼠能跳很远。' }, { text: 'Kangaroos live in Australia.', translation: '袋鼠生活在澳大利亚。' }],
    panda: [{ text: 'I see a panda.', translation: '我看到一只熊猫。' }, { text: 'The panda is eating bamboo.', translation: '熊猫在吃竹子。' }, { text: 'Pandas are black and white.', translation: '熊猫是黑白相间的。' }],
    crimson: [{ text: 'I see a crimson flower.', translation: '我看到一朵深红色的花。' }, { text: 'The sky turned crimson at sunset.', translation: '日落时天空变成了深红色。' }, { text: 'She wore a crimson dress.', translation: '她穿了一件深红色的裙子。' }],
    turquoise: [{ text: 'I see a turquoise sea.', translation: '我看到绿松石色的大海。' }, { text: 'She wore a turquoise necklace.', translation: '她戴了一条绿松石色的项链。' }, { text: 'The water is clear and turquoise.', translation: '水清澈而呈绿松石色。' }],
    magenta: [{ text: 'I see a magenta flower.', translation: '我看到一朵品红色的花。' }, { text: 'Magenta is a bright color.', translation: '品红色是亮丽的颜色。' }, { text: 'She painted the wall magenta.', translation: '她把墙刷成品红色。' }],
    lavender: [{ text: 'I see lavender flowers.', translation: '我看到薰衣草花。' }, { text: 'Lavender smells very nice.', translation: '薰衣草闻起来很香。' }, { text: 'The field is full of lavender.', translation: '田野里满是薰衣草。' }],
    coral: [{ text: 'I see a coral reef.', translation: '我看到珊瑚礁。' }, { text: 'Coral is found in the ocean.', translation: '珊瑚生长在海洋里。' }, { text: 'She likes coral color.', translation: '她喜欢珊瑚色。' }],
    olive: [{ text: 'I see an olive tree.', translation: '我看到一棵橄榄树。' }, { text: 'Olive oil is healthy.', translation: '橄榄油很健康。' }, { text: 'She added olives to the salad.', translation: '她在沙拉里加了橄榄。' }],
    maroon: [{ text: 'I see a maroon car.', translation: '我看到一辆栗色的车。' }, { text: 'Maroon is a dark red color.', translation: '栗色是深红色。' }, { text: 'He wore a maroon jacket.', translation: '他穿了一件栗色的夹克。' }],
    beige: [{ text: 'I see a beige wall.', translation: '我看到一面米色的墙。' }, { text: 'She bought a beige sofa.', translation: '她买了一张米色的沙发。' }, { text: 'The room is painted beige.', translation: '房间刷成了米色。' }],
    ivory: [{ text: 'I see an ivory statue.', translation: '我看到一座象牙雕像。' }, { text: 'The ivory tower is beautiful.', translation: '象牙塔很漂亮。' }, { text: 'She wore an ivory wedding dress.', translation: '她穿了一件象牙白的婚纱。' }],
    gold: [{ text: 'I see a gold ring.', translation: '我看到一枚金戒指。' }, { text: 'She won a gold medal.', translation: '她赢得了一枚金牌。' }, { text: 'The sun is shining like gold.', translation: '太阳像金子一样闪耀。' }],
    first: [{ text: 'I see the first star.', translation: '我看到第一颗星。' }, { text: 'This is my first time here.', translation: '这是我第一次来这里。' }, { text: 'She is the first in line.', translation: '她是排在第一位的。' }],
    second: [{ text: 'I see the second door.', translation: '我看到第二扇门。' }, { text: 'Take the second left turn.', translation: '在第二个路口左转。' }, { text: 'He is in second place.', translation: '他排在第二名。' }],
    third: [{ text: 'I see the third floor.', translation: '我看到三楼。' }, { text: 'This is my third try.', translation: '这是我第三次尝试。' }, { text: 'She sits in the third row.', translation: '她坐在第三排。' }],
    hundred: [{ text: 'I see a hundred flowers.', translation: '我看到一百朵花。' }, { text: 'The book has a hundred pages.', translation: '这本书有一百页。' }, { text: 'A hundred people came.', translation: '来了一百个人。' }],
    thousand: [{ text: 'I see a thousand stars.', translation: '我看到一千颗星星。' }, { text: 'It costs a thousand dollars.', translation: '它价值一千美元。' }, { text: 'A thousand birds flew by.', translation: '一千只鸟飞过。' }],
    million: [{ text: 'I see a million lights.', translation: '我看到一百万盏灯。' }, { text: 'The city has a million people.', translation: '这座城市有一百万人。' }, { text: 'She won a million dollars.', translation: '她赢得了一百万美元。' }],
    billion: [{ text: 'I see a billion stars.', translation: '我看到十亿颗星星。' }, { text: 'The ocean has a billion fish.', translation: '海洋里有十亿条鱼。' }, { text: 'A billion people live in cities.', translation: '十亿人生活在城市里。' }],
    half: [{ text: 'I see the half moon.', translation: '我看到半月。' }, { text: 'I ate half of the cake.', translation: '我吃了一半蛋糕。' }, { text: 'Give me half please.', translation: '请给我一半。' }],
    quarter: [{ text: 'I see a quarter of the pie.', translation: '我看到四分之一个派。' }, { text: 'It is a quarter past three.', translation: '现在是三点一刻。' }, { text: 'I found a quarter coin.', translation: '我找到一枚两角五分硬币。' }],
    double: [{ text: 'I see a double rainbow.', translation: '我看到双彩虹。' }, { text: 'Double the amount please.', translation: '请加倍。' }, { text: 'He ordered a double burger.', translation: '他点了一个双层汉堡。' }],
    parent: [{ text: 'I see a parent and child.', translation: '我看到一位家长和孩子。' }, { text: 'My parents love me very much.', translation: '我的父母非常爱我。' }, { text: 'She is a wonderful parent.', translation: '她是一位了不起的家长。' }],
    son: [{ text: 'I see a son playing.', translation: '我看到一个儿子在玩耍。' }, { text: 'Her son is five years old.', translation: '她的儿子五岁了。' }, { text: 'The son helps his father.', translation: '儿子帮助父亲。' }],
    daughter: [{ text: 'I see a daughter smiling.', translation: '我看到一个女儿在微笑。' }, { text: 'His daughter loves to draw.', translation: '他的女儿喜欢画画。' }, { text: 'The daughter hugs her mother.', translation: '女儿拥抱妈妈。' }],
    husband: [{ text: 'I see a husband and wife.', translation: '我看到一对夫妻。' }, { text: 'Her husband works in a hospital.', translation: '她的丈夫在医院工作。' }, { text: 'The husband cooks dinner.', translation: '丈夫做晚饭。' }],
    wife: [{ text: 'I see a happy wife.', translation: '我看到一位开心的妻子。' }, { text: 'His wife is a teacher.', translation: '他的妻子是一位老师。' }, { text: 'The wife reads a book.', translation: '妻子在看书。' }],
    grandparent: [{ text: 'I see a grandparent.', translation: '我看到一位祖父母。' }, { text: 'My grandparents tell me stories.', translation: '我的祖父母给我讲故事。' }, { text: 'The grandparent is very kind.', translation: '这位祖父母非常慈祥。' }],
    grandson: [{ text: 'I see a grandson playing.', translation: '我看到孙子在玩耍。' }, { text: 'His grandson visits every Sunday.', translation: '他的孙子每个星期天都来。' }, { text: 'The grandson is very smart.', translation: '孙子非常聪明。' }],
    granddaughter: [{ text: 'I see a granddaughter dancing.', translation: '我看到孙女在跳舞。' }, { text: 'Her granddaughter loves music.', translation: '她的孙女喜欢音乐。' }, { text: 'The granddaughter sings beautifully.', translation: '孙女唱歌很好听。' }],
    stepfather: [{ text: 'I see a stepfather.', translation: '我看到一位继父。' }, { text: 'Her stepfather is very supportive.', translation: '她的继父非常支持她。' }, { text: 'The stepfather drives them to school.', translation: '继父开车送他们上学。' }],
    inlaw: [{ text: 'I see my inlaw family.', translation: '我看到我的姻亲家人。' }, { text: 'She gets along with her inlaws.', translation: '她和她的姻亲相处得很好。' }, { text: 'The inlaw visit is fun.', translation: '拜访姻亲很有趣。' }],
    noodle: [{ text: 'I see a bowl of noodles.', translation: '我看到一碗面。' }, { text: 'I love eating hot noodles.', translation: '我喜欢吃热面条。' }, { text: 'The noodle soup is delicious.', translation: '面汤很美味。' }],
    soup: [{ text: 'I see a bowl of soup.', translation: '我看到一碗汤。' }, { text: 'The chicken soup smells good.', translation: '鸡汤闻起来很香。' }, { text: 'I drink soup every evening.', translation: '我每天晚上喝汤。' }],
    salad: [{ text: 'I see a green salad.', translation: '我看到一份绿色沙拉。' }, { text: 'I ordered a salad for lunch.', translation: '我午餐点了一份沙拉。' }, { text: 'The salad is fresh and healthy.', translation: '沙拉新鲜又健康。' }],
    pizza: [{ text: 'I see a pizza.', translation: '我看到一个披萨。' }, { text: 'The pizza is hot and cheesy.', translation: '披萨又热又满是芝士。' }, { text: 'Let us share a pizza.', translation: '我们一起分享披萨吧。' }],
    burger: [{ text: 'I see a burger.', translation: '我看到一个汉堡。' }, { text: 'The burger comes with fries.', translation: '汉堡配薯条。' }, { text: 'I want a burger for dinner.', translation: '我晚餐想吃汉堡。' }],
    cake: [{ text: 'I see a chocolate cake.', translation: '我看到一个巧克力蛋糕。' }, { text: 'The birthday cake has candles.', translation: '生日蛋糕上有蜡烛。' }, { text: 'She baked a cake for the party.', translation: '她为派对烤了蛋糕。' }],
    cookie: [{ text: 'I see a cookie jar.', translation: '我看到一个饼干罐。' }, { text: 'Mom baked cookies for us.', translation: '妈妈为我们烤了饼干。' }, { text: 'The cookie is crunchy and sweet.', translation: '饼干又脆又甜。' }],
    cheese: [{ text: 'I see a piece of cheese.', translation: '我看到一片奶酪。' }, { text: 'Cheese is made from milk.', translation: '奶酪是用牛奶做的。' }, { text: 'I like cheese on my sandwich.', translation: '我喜欢三明治里放奶酪。' }],
    butter: [{ text: 'I see some butter.', translation: '我看到一些黄油。' }, { text: 'Butter melts in the pan.', translation: '黄油在锅里融化了。' }, { text: 'I spread butter on toast.', translation: '我把黄油涂在吐司上。' }],
    coffee: [{ text: 'I see a cup of coffee.', translation: '我看到一杯咖啡。' }, { text: 'I drink coffee every morning.', translation: '我每天早上喝咖啡。' }, { text: 'The coffee is hot and strong.', translation: '咖啡又热又浓。' }],
    juice: [{ text: 'I see a glass of juice.', translation: '我看到一杯果汁。' }, { text: 'Orange juice is my favorite.', translation: '橙汁是我的最爱。' }, { text: 'Fresh juice is good for health.', translation: '鲜榨果汁对健康有益。' }],
    pasta: [{ text: 'I see a plate of pasta.', translation: '我看到一盘意大利面。' }, { text: 'Pasta with tomato sauce is tasty.', translation: '番茄酱意大利面很好吃。' }, { text: 'She cooks pasta for dinner.', translation: '她晚餐做意大利面。' }],
    steak: [{ text: 'I see a juicy steak.', translation: '我看到一块多汁的牛排。' }, { text: 'The steak is cooked well.', translation: '牛排做得很好。' }, { text: 'He ordered a steak at the restaurant.', translation: '他在餐厅点了一份牛排。' }],
    pancake: [{ text: 'I see a stack of pancakes.', translation: '我看到一叠煎饼。' }, { text: 'Pancakes with syrup are yummy.', translation: '加糖浆的煎饼很好吃。' }, { text: 'We have pancakes for breakfast.', translation: '我们早餐吃煎饼。' }],
    sandwich: [{ text: 'I see a sandwich.', translation: '我看到一个三明治。' }, { text: 'I made a chicken sandwich.', translation: '我做了一个鸡肉三明治。' }, { text: 'The sandwich is wrapped in paper.', translation: '三明治用纸包着。' }],
    chocolate: [{ text: 'I see a bar of chocolate.', translation: '我看到一块巧克力。' }, { text: 'Chocolate makes me happy.', translation: '巧克力让我开心。' }, { text: 'Dark chocolate is healthy.', translation: '黑巧克力很健康。' }],
    candy: [{ text: 'I see colorful candy.', translation: '我看到五颜六色的糖果。' }, { text: 'Kids love candy on Halloween.', translation: '孩子们喜欢万圣节的糖果。' }, { text: 'The candy is very sweet.', translation: '糖果很甜。' }],
    honey: [{ text: 'I see a jar of honey.', translation: '我看到一罐蜂蜜。' }, { text: 'Honey is made by bees.', translation: '蜂蜜是蜜蜂酿的。' }, { text: 'I put honey in my tea.', translation: '我在茶里加蜂蜜。' }],
    salt: [{ text: 'I see some salt.', translation: '我看到一些盐。' }, { text: 'Please pass me the salt.', translation: '请把盐递给我。' }, { text: 'Too much salt is not healthy.', translation: '盐太多不健康。' }],
    pepper: [{ text: 'I see black pepper.', translation: '我看到黑胡椒。' }, { text: 'Add some pepper to the soup.', translation: '在汤里加些胡椒。' }, { text: 'Fresh pepper tastes better.', translation: '新鲜的胡椒味道更好。' }],
    time: [{ text: 'I see the time on the clock.', translation: '我看到时钟上的时间。' }, { text: 'Time flies when you are happy.', translation: '开心的时候时间过得很快。' }, { text: 'What time is it now.', translation: '现在几点了。' }],
    day: [{ text: 'I see a sunny day.', translation: '我看到一个晴天。' }, { text: 'Every day is a new start.', translation: '每一天都是新的开始。' }, { text: 'The day is bright and warm.', translation: '天气明亮而温暖。' }],
    night: [{ text: 'I see the night sky.', translation: '我看到夜空。' }, { text: 'Good night, sweet dreams.', translation: '晚安，好梦。' }, { text: 'The stars shine at night.', translation: '星星在夜晚闪耀。' }],
    music: [{ text: 'I see music notes.', translation: '我看到音符。' }, { text: 'Music makes me feel happy.', translation: '音乐让我感到快乐。' }, { text: 'I listen to music every day.', translation: '我每天听音乐。' }],
    happy: [{ text: 'I see a happy smile.', translation: '我看到一个开心的微笑。' }, { text: 'She looks very happy today.', translation: '她今天看起来很开心。' }, { text: 'Happy people spread joy.', translation: '快乐的人传播喜悦。' }],
    beautiful: [{ text: 'I see a beautiful flower.', translation: '我看到一朵美丽的花。' }, { text: 'The sunset is so beautiful.', translation: '日落太美了。' }, { text: 'You have a beautiful voice.', translation: '你的声音很美。' }],
    important: [{ text: 'I see an important message.', translation: '我看到一条重要的消息。' }, { text: 'Education is very important.', translation: '教育非常重要。' }, { text: 'This document is important.', translation: '这份文件很重要。' }],
    different: [{ text: 'I see a different pattern.', translation: '我看到不同的图案。' }, { text: 'Everyone is different in their own way.', translation: '每个人都有自己独特的地方。' }, { text: 'Try a different approach.', translation: '试试不同的方法。' }],
    weather: [{ text: 'I see good weather today.', translation: '我看到今天天气不错。' }, { text: 'The weather is sunny and warm.', translation: '天气晴朗温暖。' }, { text: 'I check the weather every morning.', translation: '我每天早上看天气。' }],
    work: [{ text: 'I see a lot of work.', translation: '我看到很多工作。' }, { text: 'He goes to work by bus.', translation: '他坐公交车去上班。' }, { text: 'Hard work leads to success.', translation: '努力工作带来成功。' }],
    money: [{ text: 'I see some money on the table.', translation: '我看到桌子上有些钱。' }, { text: 'Money cannot buy happiness.', translation: '金钱买不到幸福。' }, { text: 'She saved money for a trip.', translation: '她为旅行存了钱。' }],
    city: [{ text: 'I see a big city.', translation: '我看到一座大城市。' }, { text: 'The city lights shine at night.', translation: '城市的灯光在夜晚闪耀。' }, { text: 'I live near the city center.', translation: '我住在市中心附近。' }],
    country: [{ text: 'I see a beautiful country.', translation: '我看到一个美丽的国家。' }, { text: 'China is a large country.', translation: '中国是一个大国。' }, { text: 'I want to visit another country.', translation: '我想去另一个国家旅行。' }],
    love: [{ text: 'I see love in their eyes.', translation: '我看到他们眼中的爱。' }, { text: 'Love makes the world go round.', translation: '爱让世界运转。' }, { text: 'I love my family.', translation: '我爱我的家人。' }],
    book: [{ text: 'I see a book on the shelf.', translation: '我看到书架上有一本书。' }, { text: 'I read a book every week.', translation: '我每周看一本书。' }, { text: 'The book is very interesting.', translation: '这本书很有趣。' }],
    water: [{ text: 'I see clear water.', translation: '我看到清澈的水。' }, { text: 'Water is essential for life.', translation: '水是生命必需的。' }, { text: 'I drink water every hour.', translation: '我每小时都喝水。' }],
    friend: [{ text: 'I see my friend coming.', translation: '我看到我的朋友来了。' }, { text: 'A good friend is a treasure.', translation: '好朋友是财富。' }, { text: 'I play with my friends after school.', translation: '放学后我和朋友一起玩。' }],
    school: [{ text: 'I see a school bus.', translation: '我看到一辆校车。' }, { text: 'I go to school every weekday.', translation: '我每个工作日都上学。' }, { text: 'The school is near my home.', translation: '学校在我家附近。' }],
    house: [{ text: 'I see a white house.', translation: '我看到一座白房子。' }, { text: 'My house is cozy and warm.', translation: '我的房子舒适温暖。' }, { text: 'They built a new house.', translation: '他们建了一座新房子。' }],
    dream: [{ text: 'I see a dream at night.', translation: '我晚上做了一个梦。' }, { text: 'Follow your dream.', translation: '追逐你的梦想。' }, { text: 'I have a dream to travel the world.', translation: '我有一个环游世界的梦想。' }],
    // weather
    sunny: [{ text: 'I see a sunny sky.', translation: '我看到晴朗的天空。' }, { text: 'It is a sunny day today.', translation: '今天是晴天。' }, { text: 'The sunny weather makes me happy.', translation: '晴朗的天气让我开心。' }],
    rainy: [{ text: 'I see a rainy day.', translation: '我看到一个雨天。' }, { text: 'It is rainy outside today.', translation: '今天外面下雨。' }, { text: 'I like the sound of rainy days.', translation: '我喜欢雨天的声音。' }],
    cloudy: [{ text: 'I see a cloudy sky.', translation: '我看到多云的天空。' }, { text: 'The sky is cloudy this morning.', translation: '今天早上天阴了。' }, { text: 'Cloudy days are good for reading.', translation: '阴天适合读书。' }],
    windy: [{ text: 'I see a windy day.', translation: '我看到一个有风的日子。' }, { text: 'It is very windy at the beach.', translation: '海滩上风很大。' }, { text: 'The windy breeze feels nice.', translation: '微风很舒服。' }],
    snowy: [{ text: 'I see a snowy mountain.', translation: '我看到一座雪山。' }, { text: 'The snowy landscape is beautiful.', translation: '雪景很美。' }, { text: 'I love snowy winter days.', translation: '我喜欢下雪的冬天。' }],
    storm: [{ text: 'I see a big storm.', translation: '我看到一场大风暴。' }, { text: 'The storm is coming soon.', translation: '暴风雨快要来了。' }, { text: 'We stayed inside during the storm.', translation: '暴风雨期间我们待在室内。' }],
    fog: [{ text: 'I see thick fog.', translation: '我看到浓雾。' }, { text: 'The fog covers the road.', translation: '雾覆盖了道路。' }, { text: 'Drive carefully in the fog.', translation: '雾天开车要小心。' }],
    rainbow: [{ text: 'I see a rainbow.', translation: '我看到一道彩虹。' }, { text: 'A rainbow appeared after the rain.', translation: '雨后出现了彩虹。' }, { text: 'The rainbow has seven colors.', translation: '彩虹有七种颜色。' }],
    lightning: [{ text: 'I see lightning in the sky.', translation: '我看到天空的闪电。' }, { text: 'Lightning is very bright.', translation: '闪电非常亮。' }, { text: 'The lightning struck the tree.', translation: '闪电击中了那棵树。' }],
    temperature: [{ text: 'I see the temperature is high.', translation: '我看到温度很高。' }, { text: 'The temperature drops at night.', translation: '夜间温度下降。' }, { text: 'Check the temperature before going out.', translation: '出门前看一下温度。' }],
    // mood
    sad: [{ text: 'I see a sad face.', translation: '我看到一张悲伤的脸。' }, { text: 'She looks sad today.', translation: '她今天看起来很伤心。' }, { text: 'It is okay to feel sad sometimes.', translation: '偶尔感到悲伤是正常的。' }],
    angry: [{ text: 'I see an angry man.', translation: '我看到一个生气的男人。' }, { text: 'He is angry about the news.', translation: '他对那则新闻很生气。' }, { text: 'Do not get angry over small things.', translation: '不要为小事生气。' }],
    excited: [{ text: 'I see excited children.', translation: '我看到兴奋的孩子们。' }, { text: 'She is excited about the trip.', translation: '她对旅行感到很兴奋。' }, { text: 'Everyone is excited for the party.', translation: '大家都为派对感到兴奋。' }],
    nervous: [{ text: 'I see a nervous student.', translation: '我看到一个紧张的学生。' }, { text: 'I feel nervous before speaking.', translation: '我说话前感到紧张。' }, { text: 'She was nervous on the first day.', translation: '她第一天很紧张。' }],
    calm: [{ text: 'I see a calm lake.', translation: '我看到平静的湖面。' }, { text: 'Stay calm and think clearly.', translation: '保持冷静并清晰思考。' }, { text: 'He is always calm under pressure.', translation: '他在压力下总是很冷静。' }],
    bored: [{ text: 'I see a bored cat.', translation: '我看到一只无聊的猫。' }, { text: 'The bored child looked for a toy.', translation: '无聊的孩子找玩具玩。' }, { text: 'I get bored when there is nothing to do.', translation: '没事做的时候我会感到无聊。' }],
    proud: [{ text: 'I see a proud mother.', translation: '我看到一位自豪的母亲。' }, { text: 'He is proud of his work.', translation: '他对自己的工作感到自豪。' }, { text: 'I am very proud of you.', translation: '我为你感到非常骄傲。' }],
    afraid: [{ text: 'I see an afraid child.', translation: '我看到一个害怕的孩子。' }, { text: 'She is afraid of spiders.', translation: '她害怕蜘蛛。' }, { text: 'Do not be afraid to try new things.', translation: '不要害怕尝试新事物。' }],
    surprised: [{ text: 'I see a surprised look.', translation: '我看到惊讶的表情。' }, { text: 'She was surprised by the news.', translation: '她对那消息感到惊讶。' }, { text: 'I am surprised you came so early.', translation: '你这么早来我很惊讶。' }],
    // sport
    run: [{ text: 'I see people run in the park.', translation: '我看到人们在公园跑步。' }, { text: 'I run every morning.', translation: '我每天早上跑步。' }, { text: 'Let us run together.', translation: '我们一起跑步吧。' }],
    swim: [{ text: 'I see fish swim in the water.', translation: '我看到鱼在水里游。' }, { text: 'She can swim very well.', translation: '她游泳游得很好。' }, { text: 'I like to swim in summer.', translation: '我喜欢夏天游泳。' }],
    jump: [{ text: 'I see a rabbit jump.', translation: '我看到一只兔子跳。' }, { text: 'The boy can jump high.', translation: '男孩能跳得很高。' }, { text: 'Jump up and down five times.', translation: '上下跳五次。' }],
    basketball: [{ text: 'I see a basketball game.', translation: '我看到一场篮球比赛。' }, { text: 'He plays basketball after school.', translation: '他放学后打篮球。' }, { text: 'The basketball team won the match.', translation: '篮球队赢得了比赛。' }],
    football: [{ text: 'I see a football field.', translation: '我看到一个足球场。' }, { text: 'Football is fun to play.', translation: '踢足球很有趣。' }, { text: 'They are watching a football match.', translation: '他们在看足球比赛。' }],
    tennis: [{ text: 'I see a tennis court.', translation: '我看到一个网球场。' }, { text: 'She enjoys playing tennis.', translation: '她喜欢打网球。' }, { text: 'The tennis player served the ball.', translation: '网球选手发球了。' }],
    cycling: [{ text: 'I see a cycling path.', translation: '我看到一条骑行道。' }, { text: 'Cycling is great exercise.', translation: '骑行是很好的锻炼。' }, { text: 'I go cycling with my friends.', translation: '我和朋友一起去骑行。' }],
    skiing: [{ text: 'I see a skiing slope.', translation: '我看到滑雪坡。' }, { text: 'Skiing down the mountain is thrilling.', translation: '从山上滑下来很刺激。' }, { text: 'They are learning how to ski.', translation: '他们在学滑雪。' }],
    exercise: [{ text: 'I see people exercise outside.', translation: '我看到人们在户外锻炼。' }, { text: 'Daily exercise is important.', translation: '每天锻炼很重要。' }, { text: 'I do morning exercise every day.', translation: '我每天做晨练。' }],
    match: [{ text: 'I see an exciting match.', translation: '我看到一场激动人心的比赛。' }, { text: 'The match was very close.', translation: '比赛非常接近。' }, { text: 'Who won the match yesterday.', translation: '昨天的比赛谁赢了。' }],
  };

  for (const w of words) {
    const key = w.word.toLowerCase();
    const existingWord = await prisma.word.findUnique({ where: { word: w.word } });
    if (existingWord && sentencePatterns[key]) {
      const sentences = sentencePatterns[key].map((item, idx) => ({
        wordId: existingWord.id,
        text: item.text,
        translation: item.translation,
        level: idx + 1,
      }));
      await prisma.sentence.createMany({ data: sentences });
    }
  }
  console.log('✅ Sentences seeded for all words');

  console.log('🎉 Database seeding complete!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
